sudo: required

language: go

services:
  - docker

script:
  - go test -v -short ./...

after_success:
  - if [ ! -z "$TRAVIS_TAG" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    script/docker-build.sh "rerorero/netscaler-exporter:$TRAVIS_TAG";
    fi
